name: Run Playbook

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          configuration: |
            [defaults]
            inventory = inventory.ini
            remote_user = root
          playbook: playbook.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
        